### ISSUE TITLE
OpenMP required in CMake

### ISSUE THREAD

**Issue by kgerheiser** [GeorgeGayno-NOAA/UFS_UTILS#8]
OpenMP is marked as optional, but it's really required.

In the NCEPLIBS umbrella build we mark OpenMP off by default here:

https://github.com/NOAA-EMC/NCEPLIBS/blob/76008141f1d13120c87f32db8e1489b7528898fa/CMakeLists.txt#L58

Then, in UFS_UTILS OpenMP it is on by default here https://github.com/GeorgeGayno-NOAA/UFS_UTILS/blob/6008a2221b9790b46da2b747b86f354c9765c8f0/CMakeLists.txt#L42

However, this overrides the top-level OPENMP variable, so it's set to off.

Then in `global_chgres` `num_parthds.f90` is added which uses `omp_get_max_threads()` here:

https://github.com/GeorgeGayno-NOAA/UFS_UTILS/blob/6008a2221b9790b46da2b747b86f354c9765c8f0/sorc/global_chgres.fd/CMakeLists.txt#L9

This file is always added and always uses OpenMP and won't build if OpenMP is set to false.

And then, it's only linked if it's found, which it is not:

https://github.com/GeorgeGayno-NOAA/UFS_UTILS/blob/6008a2221b9790b46da2b747b86f354c9765c8f0/sorc/global_chgres.fd/CMakeLists.txt#L47

So, using OpenMP is not optional and if you turn the option to false it won't build. My suggestion is to add an `ifdef` to this or to require OpenMP.

**Comment by GeorgeGayno-NOAA** [comment]
Kyle, I just saw this issue.  For some reason, GitHub did not notify me that you opened this.  You can also add your comments to this issue: https://github.com/NOAA-EMC/UFS_UTILS/issues/91

I will test your suggestion.
